name: Deploy Angular Project to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Match this to your project's Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the Angular app
      run: npm run build -- --prod

    - name: Deploy to GitHub Pages
      env:
        CI: true
      run: |
        npx angular-cli-ghpages --dir=dist/aws-s3-project --no-silent
